# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_ffmpeg6numpy1.22python3.10.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.10.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.10.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.10.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.10.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.10.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.8.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.8.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.8.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.8.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.8.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.8.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.9.____73_pypyqt_version5:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.9.____73_pypyqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.9.____73_pypyqt_version6:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.9.____73_pypyqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.9.____73_pypyqt_versionnone:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.9.____73_pypyqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.9.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.9.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.9.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.9.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.22python3.9.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg6numpy1.22python3.9.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.23python3.11.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg6numpy1.23python3.11.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.23python3.11.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg6numpy1.23python3.11.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.23python3.11.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg6numpy1.23python3.11.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.26python3.12.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg6numpy1.26python3.12.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.26python3.12.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg6numpy1.26python3.12.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg6numpy1.26python3.12.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg6numpy1.26python3.12.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.10.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.10.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.10.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.10.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.10.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.10.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.8.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.8.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.8.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.8.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.8.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.8.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.9.____73_pypyqt_version5:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.9.____73_pypyqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.9.____73_pypyqt_version6:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.9.____73_pypyqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.9.____73_pypyqt_versionnone:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.9.____73_pypyqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.9.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.9.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.9.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.9.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.22python3.9.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg7numpy1.22python3.9.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.23python3.11.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg7numpy1.23python3.11.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.23python3.11.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg7numpy1.23python3.11.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.23python3.11.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg7numpy1.23python3.11.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.26python3.12.____cpythonqt_version5:
        CONFIG: linux_64_ffmpeg7numpy1.26python3.12.____cpythonqt_version5
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.26python3.12.____cpythonqt_version6:
        CONFIG: linux_64_ffmpeg7numpy1.26python3.12.____cpythonqt_version6
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_64_ffmpeg7numpy1.26python3.12.____cpythonqt_versionnone:
        CONFIG: linux_64_ffmpeg7numpy1.26python3.12.____cpythonqt_versionnone
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg6numpy1.22python3.10.____cpython:
        CONFIG: linux_aarch64_ffmpeg6numpy1.22python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg6numpy1.22python3.8.____cpython:
        CONFIG: linux_aarch64_ffmpeg6numpy1.22python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg6numpy1.22python3.9.____73_pypy:
        CONFIG: linux_aarch64_ffmpeg6numpy1.22python3.9.____73_pypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg6numpy1.22python3.9.____cpython:
        CONFIG: linux_aarch64_ffmpeg6numpy1.22python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg6numpy1.23python3.11.____cpython:
        CONFIG: linux_aarch64_ffmpeg6numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg6numpy1.26python3.12.____cpython:
        CONFIG: linux_aarch64_ffmpeg6numpy1.26python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg7numpy1.22python3.10.____cpython:
        CONFIG: linux_aarch64_ffmpeg7numpy1.22python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg7numpy1.22python3.8.____cpython:
        CONFIG: linux_aarch64_ffmpeg7numpy1.22python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg7numpy1.22python3.9.____73_pypy:
        CONFIG: linux_aarch64_ffmpeg7numpy1.22python3.9.____73_pypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg7numpy1.22python3.9.____cpython:
        CONFIG: linux_aarch64_ffmpeg7numpy1.22python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg7numpy1.23python3.11.____cpython:
        CONFIG: linux_aarch64_ffmpeg7numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_aarch64_ffmpeg7numpy1.26python3.12.____cpython:
        CONFIG: linux_aarch64_ffmpeg7numpy1.26python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg6numpy1.22python3.10.____cpython:
        CONFIG: linux_ppc64le_ffmpeg6numpy1.22python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg6numpy1.22python3.8.____cpython:
        CONFIG: linux_ppc64le_ffmpeg6numpy1.22python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg6numpy1.22python3.9.____73_pypy:
        CONFIG: linux_ppc64le_ffmpeg6numpy1.22python3.9.____73_pypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg6numpy1.22python3.9.____cpython:
        CONFIG: linux_ppc64le_ffmpeg6numpy1.22python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg6numpy1.23python3.11.____cpython:
        CONFIG: linux_ppc64le_ffmpeg6numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg6numpy1.26python3.12.____cpython:
        CONFIG: linux_ppc64le_ffmpeg6numpy1.26python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg7numpy1.22python3.10.____cpython:
        CONFIG: linux_ppc64le_ffmpeg7numpy1.22python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg7numpy1.22python3.8.____cpython:
        CONFIG: linux_ppc64le_ffmpeg7numpy1.22python3.8.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg7numpy1.22python3.9.____73_pypy:
        CONFIG: linux_ppc64le_ffmpeg7numpy1.22python3.9.____73_pypy
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg7numpy1.22python3.9.____cpython:
        CONFIG: linux_ppc64le_ffmpeg7numpy1.22python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg7numpy1.23python3.11.____cpython:
        CONFIG: linux_ppc64le_ffmpeg7numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_ffmpeg7numpy1.26python3.12.____cpython:
        CONFIG: linux_ppc64le_ffmpeg7numpy1.26python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
    maxParallel: 28
  timeoutInMinutes: 360
  variables: {}

  steps:
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)